### ISSUE TITLE
Wrong url path in tags page.

### ISSUE THREAD

**Issue by rodrigopandini** [joshgerdes/jekyll-uno#39]
Hi @joshgerdes Great theme!

For some reason seems that last commit ([d1b9a46](https://github.com/joshgerdes/jekyll-uno/commit/d1b9a46a04c23837b181ca43d50184ba8b4b9616)) is not working for me.
It is pointing to IP: 0.0.7.224 ?
Do not respect the correct url concatenation.
For example:
Correctly: 127.0.0.1:4000/2016/welcome-to-jekyll/
In tags page: 0.0.7.224/welcome-to-jekyll/

I need configure something else in _config.yml?

``` yml
...
url: 'http://mywebsite.com'
baseurl: '/'
...
```
